service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends bash unzip curl jq libxml2-utils docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80

script:
- bash gradlew >/dev/null 2>&1
- java -jar ./build/libs/*.jar &
- wait_for 8080
- http :8080 message=hey!
- http :8080 message=ho!
- http :8080
- stop_any 8080 80
#
- bash ./build/libs/*.jar &
- wait_for 8080
- http :8080 message=hey!
- http :8080 message=ho!
- http :8080
- stop_any 8080 80
#
- bash gradlew composeUp
- http :8080 message=hey!
- http :8080 message=ho!
- http :8080
- bash gradlew composeDown
#
- bash mvnw >/dev/null 2>&1
- java -jar ./target/*.jar &
- wait_for 8080
- sleep 10
- http :8080 message=hey!
- http :8080 message=ho!
- http :8080
- stop_any 8080 80
#
- bash ./target/*.jar &
- wait_for 8080
- sleep 10
- http :8080 message=hey!
- http :8080 message=ho!
- http :8080
- stop_any 8080 80
#
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- sleep 30
- http :8080
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
